version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '9jg@5VvnYFMfpdi'
      MYSQL_DATABASE: 'digitalhub'
      MYSQL_USER: 'digitalhub'
      MYSQL_PASSWORD: 'aC#z&DMVfd'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '9jg@5VvnYFMfpdi'


volumes:
  mysql_data:
