# Generated by Django 5.0.6 on 2024-09-03 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='review_images/')),
                ('body', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='review_images/')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtext', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('icon', models.ImageField(upload_to='service_icons/')),
                ('header_image', models.ImageField(upload_to='service_images/')),
                ('description', ckeditor.fields.RichTextField()),
                ('bottom_image', models.ImageField(upload_to='service_images/')),
                ('benefits', models.ManyToManyField(related_name='services', to='core.benefit')),
                ('stand_alone_plans', models.ManyToManyField(related_name='services', to='payment.standaloneplan')),
            ],
        ),
    ]
