# Generated by Django 5.0.6 on 2024-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_team_service_icon_service_subtext'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='plans',
        ),
        migrations.AddField(
            model_name='service',
            name='stand_alone_plans',
            field=models.ManyToManyField(related_name='services', to='payment.standaloneplan'),
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
