# Generated by Django 5.0.6 on 2024-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standaloneplan',
            name='duration_type',
            field=models.CharField(choices=[('month', 'month'), ('per_video', 'per video'), ('per_page', 'per page'), ('per_strategy', 'per strategy'), ('per_hour', 'per hour'), ('per_setup', 'per setup'), ('starting_price', 'starting price')], default='month', max_length=50),
        ),
    ]
