# Generated by Django 5.0.6 on 2024-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleplan',
            name='plan_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='standaloneplan',
            name='plan_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
