# Generated by Django 5.0.6 on 2024-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_standaloneplan_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standaloneplan',
            name='duration_type',
            field=models.CharField(choices=[('month', 'month'), ('per video', 'per video'), ('per page', 'per page'), ('per strategy', 'per strategy'), ('per hour', 'per hour'), ('per setup', 'per setup'), ('starting price', 'starting price')], default='month', max_length=50),
        ),
    ]
