# Generated by Django 5.0.6 on 2024-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleplan',
            name='payment_mode',
            field=models.CharField(choices=[('payment', 'Payment'), ('subscription', 'Subscription')], default='subscription', max_length=50),
        ),
        migrations.AddField(
            model_name='standaloneplan',
            name='payment_mode',
            field=models.CharField(choices=[('payment', 'Payment'), ('subscription', 'Subscription')], default='subscription', max_length=50),
        ),
    ]
