# Generated by Django 5.0.6 on 2024-09-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_bundleplan_payment_mode_standaloneplan_payment_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standaloneplan',
            old_name='plan_id',
            new_name='price_id',
        ),
    ]
